### ISSUE TITLE
Old Kotlin version is required

### ISSUE THREAD

**Issue by AlexBrightwater** [horizr/one-time-overrides#1]
I tried to use this mod alongside other mods that also require Fabric Language Kotlin. Thus I already have the newest version installed. But this mod requires an older version. Using both doesn't work. So maybe this mod can update its dependency to the newest Kotlin.

**Comment by moritzruth** [comment]
I'll try to look into it at the weekend.

**Comment by moritzruth** [comment]
I don’t think I’ll be able to fix this anytime soon. Feel free to create a pull request.
